# Dockerfile.frontend

FROM python:3.11-slim

WORKDIR /app

# Copy everything for frontend
COPY requirements-frontend.txt .
# Убираем ненужную ссылку на PyTorch, если Frontend его не использует
RUN pip install --no-cache-dir -r requirements-frontend.txt

# Copy the Streamlit script
COPY frontend/app.py ./app.py

# Open standard Streamlit port
EXPOSE 8501

# Run Streamlit
CMD ["streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]